platform :ios, '12.0'
use_frameworks!

target 'CreativeKitSample' do
  pod 'SnapSDK', :subspecs => ['SCSDKCreativeKit']
  pod 'FLAnimatedImage'
end

target 'CreativeKitSampleTests' do

end

target 'CreativeKitSampleUITests' do

end
